openapi: "3.0.3"
info:
  title: "SpisOpBackend API"
  description: "SpisOpBackend API"
  version: "1.0.0"
servers:
  - url: "https://SpisOpBackend"
paths:
  /user/{userId}/communities:
    get:
      summary: "GET user/{userId}/communities"
      operationId: "getCommunitiesByUserId"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CommunityDTO"
components:
  schemas:
    Address:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        streetName:
          type: "string"
        postalCode:
          type: "integer"
          format: "int32"
        city:
          type: "string"
        houseNumber:
          type: "string"
        countryCode:
          type: "string"
        country:
          type: "string"
    Community:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        createdBy:
          $ref: "#/components/schemas/User"
        users:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
    Company:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        address:
          $ref: "#/components/schemas/Address"
        managers:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
    User:
      type: "object"
      properties:
        id:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        username:
          type: "string"
        profilePicture:
          type: "string"
        address:
          $ref: "#/components/schemas/Address"
        communities:
          type: "array"
          items:
            $ref: "#/components/schemas/Community"
        companies:
          type: "array"
          items:
            $ref: "#/components/schemas/Company"
    CommunityDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        createdBy:
          $ref: "#/components/schemas/User"
        users:
          type: "array"
          items:
            $ref: "#/components/schemas/User"