name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches to ensure we can access main

      # Step 2: Set up JDK for Java-based tests
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Step 3: Cache Maven dependencies (for backend)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies (for backend, without running tests)
      - name: Install Maven dependencies
        working-directory: backend
        run: mvn install -DskipTests

      # Step 5: Set environment variables for H2 and your application
      - name: Set Environment Variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      # Step 6: Start your backend application (API)
      - name: Start Backend Application
        working-directory: backend
        run: |
          mvn spring-boot:run &  # Start the application in the background
          sleep 20 # Wait for the app to start

      # Step 7: Run Unit Tests (for backend, always run on branches except main)
      - name: Run Unit Tests
        working-directory: backend
        run: mvn test

      # Step 8: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 9: Login to Postman CLI using API key from GitHub Secrets
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 10: Run Postman API Tests using the test database
      - name: Run API Tests
        run: |
          postman collection run "27701941-e6b1b59c-0565-4209-9936-5834d840a9c2" -e "27701941-ffcc469a-a8ad-489a-b4b6-f6079a5697a7" \
            --env-var base_url="$BASE_URL"
