name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "23"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies
        working-directory: backend
        run: mvn verify

      - name: Set Environment Variables
        run: echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      - name: Start Backend Application
        working-directory: backend
        run: |
          mvn spring-boot:run -Dspring-boot.run.arguments=--spring.profiles.active=test &
          sleep 5

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Start Frontend Application
        working-directory: frontend
        run: |
          npm run dev &
          sleep 5

      - name: Install Cypress
        working-directory: frontend
        run: npm install cypress --save-dev

      - name: Run Cypress Tests
        working-directory: frontend
        run: npx cypress run --config baseUrl=http://localhost:5173

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Postman API Tests
        run: |
          postman collection run "27701941-e6b1b59c-0565-4209-9936-5834d840a9c2" -e "27701941-ffcc469a-a8ad-489a-b4b6-f6079a5697a7" \
            --env-var base_url="$BASE_URL"

      - name: Build and analyze with SonarCloud
        working-directory: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=albe194e_TestMandatory1