name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches to ensure we can access main

      # Step 2: Set up JDK for Java-based tests
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "23"

      # Step 3: Cache Maven dependencies (for backend)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies (for backend, without running tests)
      - name: Install Maven dependencies
        working-directory: backend
        run: mvn install -DskipTests

      # Step 5: Set environment variables
      - name: Set Environment Variables
        run: |
          echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      # Step 6: Copy application-prod.properties to application.properties for deployment
      - name: Use prod config for GitHub Actions
        working-directory: backend/src/main/resources
        run: cp application-prod.properties application.properties

      # Step 7: Start the backend application using the updated prod config
      - name: Start Backend Application
        working-directory: backend
        run: |
          mvn spring-boot:run -Ddebug &
          sleep 5

      # Step 8: Run Unit Tests (uses H2 in-memory database)
      - name: Run Unit Tests
        working-directory: backend
        run: mvn test -Dspring.profiles.active=test -e -X


      # Step 9: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 10: Login to Postman CLI using API key from GitHub Secrets
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 11: Run Postman API Tests using the test database
      - name: Run API Tests
        run: |
          postman collection run "27701941-e6b1b59c-0565-4209-9936-5834d840a9c2" -e "27701941-ffcc469a-a8ad-489a-b4b6-f6079a5697a7" \
            --env-var base_url="$BASE_URL"
